### ISSUE TITLE
Fail/Retry when Loading of Cloud Config Fails

### ISSUE THREAD

**Issue by fabb** [MattRoss34/spring-cloud-config#14]
Currently, according to the documentation, a failed load of the cloud config silently fails and falls back to the local config:

> Keep in mind, however, any error encountered while reaching the remote property sources is currently ignored. Because of this, it is recommended that the properties defined in application.yml be kept up to date and represent the most current state of the application (as much as reasonably possible).

This is far from ideal. The local config contains completely different config options than the profiles of different environments. This is a blocker for us using this package.

=> Could you add an option to not fail silently, but rather have no fallback and prevent the application from starting up (unless started locally or for test)?

Automatic retry would also be nice, the Spring Java Implementation Client supports that as well:

http://cloud.spring.io/spring-cloud-config/2.0.x/single/spring-cloud-config.html#config-client-retry

> If you expect that the config server may occasionally be unavailable when your app starts, you can ask it to keep trying after a failure. First you need to set spring.cloud.config.failFast=true, and then you need to add spring-retry and spring-boot-starter-aop to your classpath. The default behaviour is to retry 6 times with an initial backoff interval of 1000ms and an exponential multiplier of 1.1 for subsequent backoffs. You can configure these properties (and others) using spring.cloud.config.retry.* configuration properties.

**Comment by MattRoss34** [comment]
@fabb thanks for the great issue!  I agree that having a retry is an important feature.  I've had this on my radar since the beginning but haven't needed it myself.  I'm happy to give it a go but please feel free to contribute with a PR if you'd like to.

I'd like to point out though that you should be able to define your environment-specific configs in your local config file(s).  Refer to the sections on: [Support for Profiles in Multi-Document Yaml](https://github.com/MattRoss34/spring-cloud-config#support-for-profiles-in-multi-document-yaml) and [Support for Profile-Specific File Names](https://github.com/MattRoss34/spring-cloud-config#support-for-profile-specific-file-names).

If you think you have a different case that wouldn't work this way let me know.  I'd be happy to discuss.

**Comment by MattRoss34** [comment]
@fabb fyi I'm about to merge a PR that adds the fail-fast feature and will close this issue.  Fail fast was the main ask here, whereas retry was an added bonus.  I might look into the retry behavior next, so feel free to open a separate issue for that if it's high priority for you.

Thanks again for the great request.  Keep 'em comin if you have more needs.

**Comment by MattRoss34** [comment]
@fabb #35 implements retry.  Let me know if you have any feedback.

**Comment by fabb** [comment]
Very cool that you also allow to set the interval additional to retry count, cheers!
